function T = struct2table_with_mode(metrics,info,mode)
T = table( string(mode), string(info.scheme), double(info.period_px), ...
           double(info.plot_row), double(info.row_score), ...
           double(info.M_before_mean), double(info.M_after_mean), ...
           double(metrics.THD), double(metrics.orthogonality), ...
           double(metrics.amp_rel_err), ...
           double(metrics.phase_deg(1)), double(metrics.phase_deg(2)), double(metrics.phase_deg(3)), ...
           double(metrics.coverage_Mgt0p2), ...
           'VariableNames', {'mode','scheme','period_px','row','row_score', ...
                             'M_before','M_after','THD','orth','amp_err','phi12','phi23','phi34','coverage'});
end
